version: 2
jobs:
  build:
    working_directory: ~/st2client
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
